// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Расширение типа глобального объекта window для TypeScript
declare global {
  interface Window {
    APP_CONFIG?: {
      API_URL?: string;
      SUPABASE_URL?: string;
      SUPABASE_ANON_KEY?: string;
      VERSION?: string;
      ENV?: "development" | "production";
    };
  }
}

// Используем переменные окружения Vite или значения по умолчанию
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://xcheceveynzdugmgwrmi.supabase.co";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjaGVjZXZleW56ZHVnbWd3cm1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTI3NTQsImV4cCI6MjA2MTY4ODc1NH0.EtTP-fNb5UrCs6nB_O8mds8oTTBJCeWh1CmfmzDiuds";

// Позволяем приложению переопределить значения через window.APP_CONFIG
const getSupabaseUrl = () => window.APP_CONFIG?.SUPABASE_URL || SUPABASE_URL;
const getSupabaseKey = () => window.APP_CONFIG?.SUPABASE_ANON_KEY || SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(getSupabaseUrl(), getSupabaseKey());

// Для удобства разработки и отладки
if (import.meta.env.DEV) {
  console.log('Supabase клиент инициализирован с URL:', getSupabaseUrl());
}
